### ISSUE TITLE
[Request] Video Controls

### ISSUE THREAD

**Issue by MogiLogi** [wxxsw/GSPlayer#26]
Hello, Thank you for this awesome code, it would be nice if you can add basic controls over the layout which can be disabled and enabled.

Best regards.

**Comment by wxxsw** [comment]
Hello, maybe I can't add default controls to GSPlayer, because actually every real project has its own user interface. But I can consider improving the Demo and providing a basic control layout, developers can directly use the code in the Demo in their own projects. I'm still busy lately, I will do it when I have time.

**Comment by MogiLogi** [comment]
Thank you, I have created one it's not perfect, but maybe you can improve it and put it for others

[
[Control.zip](https://github.com/wxxsw/GSPlayer/files/6069485/Control.zip)
](url)

**Comment by wxxsw** [comment]
Thank you, I have added it to the demo.
